// Torc - Copyright 2011 University of Southern California.  All Rights Reserved.
// $HeadURL$
// $Id$

// This program is free software: you can redistribute it and/or modify it under the terms of the 
// GNU General Public License as published by the Free Software Foundation, either version 3 of the 
// License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
// without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See 
// the GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License along with this program.  If 
// not, see <http://www.gnu.org/licenses/>.

/// \file
/// \brief Static definition of the Virtex6 class.
/// \details This is a generated file.  Please modify with care.

#include "torc/bitstream/Virtex6.hpp"

namespace torc {
namespace bitstream {

	enum { Empty = Virtex6::eColumnTypeEmpty, Bram = Virtex6::eColumnTypeBram, 
		Clb = Virtex6::eColumnTypeClb, Clock = Virtex6::eColumnTypeClock, 
		Dsp = Virtex6::eColumnTypeDsp, Gtx = Virtex6::eColumnTypeGtx, 
		Iob = Virtex6::eColumnTypeIob, END = boost::uint32_t(-1) };

	// xc6vcx75t static device information.
	boost::uint32_t xc6vcx75tColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vcx75t(22733, 127, 179, xc6vcx75tColumns);

	// xc6vcx130t static device information.
	boost::uint32_t xc6vcx130tColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vcx130t(37769, 211, 179, xc6vcx130tColumns);

	// xc6vcx195t static device information.
	boost::uint32_t xc6vcx195tColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vcx195t(52961, 211, 251, xc6vcx195tColumns);

	// xc6vcx240t static device information.
	boost::uint32_t xc6vcx240tColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vcx240t(63503, 253, 251, xc6vcx240tColumns);

	// xc6vhx250t static device information.
	boost::uint32_t xc6vhx250tColumns[] = { Gtx, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vhx250t(65274, 253, 258, xc6vhx250tColumns);

	// xc6vhx255t static device information.
	boost::uint32_t xc6vhx255tColumns[] = { Gtx, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vhx255t(65274, 253, 258, xc6vhx255tColumns);

	// xc6vhx380t static device information.
	boost::uint32_t xc6vhx380tColumns[] = { Gtx, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vhx380t(97782, 379, 258, xc6vhx380tColumns);

	// xc6vhx565t static device information.
	boost::uint32_t xc6vhx565tColumns[] = { Gtx, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vhx565t(132650, 379, 350, xc6vhx565tColumns);

	// xc6vlx75t static device information.
	boost::uint32_t xc6vlx75tColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vlx75t(22733, 127, 179, xc6vlx75tColumns);

	// xc6vlx130t static device information.
	boost::uint32_t xc6vlx130tColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vlx130t(37769, 211, 179, xc6vlx130tColumns);

	// xc6vlx195t static device information.
	boost::uint32_t xc6vlx195tColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vlx195t(52961, 211, 251, xc6vlx195tColumns);

	// xc6vlx240t static device information.
	boost::uint32_t xc6vlx240tColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vlx240t(63503, 253, 251, xc6vlx240tColumns);

	// xc6vlx365t static device information.
	boost::uint32_t xc6vlx365tColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vlx365t(84755, 253, 335, xc6vlx365tColumns);

	// xc6vlx550t static device information.
	boost::uint32_t xc6vlx550tColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vlx550t(126965, 379, 335, xc6vlx550tColumns);

	// xc6vlx760 static device information.
	boost::uint32_t xc6vlx760Columns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Empty, Iob, END };
	DeviceInfo xc6vlx760(163349, 379, 431, xc6vlx760Columns);

	// xc6vsx315t static device information.
	boost::uint32_t xc6vsx315tColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vsx315t(86273, 253, 341, xc6vsx315tColumns);

	// xc6vsx475t static device information.
	boost::uint32_t xc6vsx475tColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vsx475t(129239, 379, 341, xc6vsx475tColumns);

	// xc6vlx75tl static device information.
	boost::uint32_t xc6vlx75tlColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Iob, Gtx, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Gtx, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clock, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vlx75tl(22733, 127, 179, xc6vlx75tlColumns);

	// xc6vlx130tl static device information.
	boost::uint32_t xc6vlx130tlColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Iob, Gtx, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Gtx, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clock, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vlx130tl(37769, 211, 179, xc6vlx130tlColumns);

	// xc6vlx195tl static device information.
	boost::uint32_t xc6vlx195tlColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Gtx, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Gtx, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clock, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vlx195tl(52961, 211, 251, xc6vlx195tlColumns);

	// xc6vlx240tl static device information.
	boost::uint32_t xc6vlx240tlColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Gtx, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Gtx, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clock, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vlx240tl(63503, 253, 251, xc6vlx240tlColumns);

	// xc6vlx365tl static device information.
	boost::uint32_t xc6vlx365tlColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Gtx, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Gtx, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clock, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vlx365tl(84755, 253, 335, xc6vlx365tlColumns);

	// xc6vlx550tl static device information.
	boost::uint32_t xc6vlx550tlColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Gtx, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Gtx, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clock, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vlx550tl(126965, 379, 335, xc6vlx550tlColumns);

	// xc6vlx760l static device information.
	boost::uint32_t xc6vlx760lColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Gtx, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Gtx, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Empty, Empty, Iob, END };
	DeviceInfo xc6vlx760l(163349, 379, 431, xc6vlx760lColumns);

	// xc6vsx315tl static device information.
	boost::uint32_t xc6vsx315tlColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Gtx, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Gtx, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clock, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vsx315tl(86273, 253, 341, xc6vsx315tlColumns);

	// xc6vsx475tl static device information.
	boost::uint32_t xc6vsx475tlColumns[] = { Iob, Empty, Empty, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Iob, Gtx, Empty, Empty, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Clock, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Gtx, Iob, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Empty, Dsp, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Empty, Dsp, Empty, Empty, Clb, Empty, Clb, Empty, Empty, Bram, Empty, Clb, Empty, Clb, Empty, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clb, Empty, Clock, Bram, Empty, Empty, Empty, Gtx, END };
	DeviceInfo xc6vsx475tl(129239, 379, 341, xc6vsx475tlColumns);

} // namespace bitstream
} // namespace torc
